# Generated by Django 3.1.2 on 2020-12-01 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auto_20201201_1438'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
