# Generated by Django 3.1.2 on 2020-12-01 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_delete_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('FOD', 'FOOD'), ('FAS', 'FASHION'), ('TOY', 'TOYS'), ('ELC', 'ELECTRONICS'), ('HOM', 'HOME'), ('SLR', 'SOLAR'), ('EDU', 'EDUCATION'), ('TEC', 'TECHNOLOGY'), ('PLT', 'PLANTS'), ('ANI', 'ANIMALS')], default='FOD', max_length=3)),
            ],
        ),
        migrations.AddField(
            model_name='listing',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='listings', to='auctions.Category'),
        ),
    ]
