# Generated by Django 3.1.2 on 2020-12-05 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='highest_bidder',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
