# Generated by Django 3.1.2 on 2020-12-05 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_auto_20201205_2142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='highest_bidder',
        ),
    ]
