# Generated by Django 3.1.2 on 2020-12-06 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0026_auto_20201206_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='winner',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
