# Generated by Django 3.1.2 on 2020-12-06 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0027_bid_winner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='winner',
        ),
    ]
