# Generated by Django 3.1.2 on 2020-12-07 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0030_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(blank=True, choices=[(0, 'FOOD'), (1, 'FASHION'), (2, 'TOYS'), (3, 'ELECTRONICS'), (4, 'HOME'), (5, 'SOLAR'), (6, 'EDUCATION'), (7, 'TECHNOLOGY'), (8, 'PLANTS'), (9, 'ANIMALS')], default=0, max_length=3, null=True),
        ),
    ]
