# Generated by Django 3.1.2 on 2020-12-07 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0032_auto_20201207_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='category',
        ),
    ]
