# Generated by Django 3.1.2 on 2020-12-09 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0034_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winner',
            name='message',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
