# Generated by Django 3.1.2 on 2020-12-09 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0035_auto_20201209_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winner',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bid_winner', to=settings.AUTH_USER_MODEL),
        ),
    ]
