# Generated by Django 3.1.2 on 2020-12-09 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0039_auto_20201209_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
